services:
  - type: web
    name: compression-service
    env: python
    region: oregon
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y libmagic1
      cd api && pip install -r requirements.txt
      cd ../pcc && pip install -r requirements.txt
    startCommand: cd api && uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
